spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.6.120/sell?characterEncoding=utf-8&useSSL=false
#  jpa:
#    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.6.120
    port: 6379
server:
  context-path: /sell
logging:
  level:
    com.sml.pojo.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml








